# Generated by Django 4.0.3 on 2022-08-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrkshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
