# Generated by Django 4.0.3 on 2022-08-31 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrkshopapp', '0004_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
