# Generated by Django 4.0.3 on 2022-08-31 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrkshopapp', '0005_alter_request_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(auto_now=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrkshopapp.request')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrkshopapp.technician')),
            ],
        ),
    ]
