# Generated by Django 4.0.3 on 2022-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrkshopapp', '0006_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='edate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sdate',
            field=models.DateField(null=True),
        ),
    ]
