# Generated by Django 4.0.3 on 2022-10-05 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wrkshopapp', '0007_schedule_edate_alter_schedule_sdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='uid',
        ),
        migrations.AddField(
            model_name='feedback',
            name='sid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='wrkshopapp.schedule'),
        ),
    ]
