# Generated by Django 4.0.3 on 2022-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrkshopapp', '0008_remove_feedback_uid_feedback_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='amount',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
